config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  has_many :articles, dependent: :destroy

  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: {minimum: 3, maximum: 25}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            length: {maximum: 105},
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # makes it available to views, too
  helper_method :current_user, :logged_in?
  def current_user
    # returns @current_user if the User.find has been validated.
    # If not, it will query the database.
    # This stops unnecessary querying.
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    # !! turns current user into a bool
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:alert] = "You must be logged in to perform that action."
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(:page => params[:page], :per_page => 3)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def edit
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article."
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  def new
    @category = Category.new
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    #redirect_to articles_path if logged_in?
  end

  def about
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # signs a user in once they sign up
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.username}! You have successfully signed up. "
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update

    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully update."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @articles = @user.articles.paginate(:page => params[:page], :per_page => 3)
  end

  def index
    @users = User.paginate(:page => params[:page], :per_page => 3)
  end

  def destroy
    @user.destroy
    # important or will cause issues with session id
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articles_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own profile."
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username)
  end


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Author</th>
    <th colspan="3">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @articles.each do |article| %>

    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <% if article.user %>
      <td>by <%= link_to article.user.username, user_path(article.user)  %></td>
        <% end %>
      <td><%= link_to 'Show', article_path(article) %></td>
      <% if logged_in? && (article.user == current_user || current_user.admin?) %>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Delete', article_path(article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
      <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevent the article from being saved:</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @article, data: { turbo: false }, local: true) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>
<%= link_to 'Return to articles listing', articles_path %>

app/views/articles/index.html.erb
<% if logged_in? %>
  <%= link_to current_user.username, user_path(current_user) %>
  <%= link_to 'Log out', logout_path, data: { turbo_method: :delete } %>
<% else %>
  <%= link_to 'Log in', login_path %>
  <%= link_to 'Sign Up', signup_path %>
<% end %>
<h1>Articles Listing Page</h1>

<%= will_paginate @articles %>
<%= render 'article' %>
<p> <%= link_to 'Create New Article', new_article_path %> </p>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>

<%= link_to 'Return to articles listing', articles_path %>

app/views/articles/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<h1>Testing Article</h1>
<p><strong>Title: </strong> <%= @article.title %></p>
<p><strong>Description: </strong> <%= @article.description %></p>
by <%= @article.user.username if @article.user %>
<%= link_to gravatar_for(@article.user), user_path(@article.user) %>
<% if logged_in? && (@article.user == current_user || current_user.admin?) %>
  <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to 'Delete', article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %> |
<% end %>
<%= link_to 'Return to articles listing', articles_path %>

</body>
</html>

app/views/categories/index.html.erb
<h1>Categories</h1>

<%= will_paginate @categories %>


<% @categories.each do |category| %>
  <%= link_to category.name, category_path(category) %>

<% end %>

app/views/categories/new.html.erb
<h1>Create a new category</h1>
<%= form_with(model: @category, local: true) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>

app/views/categories/show.html.erb
Category: <%= @category.name %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary rounded" aria-label="Thirteenth navbar example">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample11" aria-controls="navbarsExample11" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse d-lg-flex" id="navbarsExample11">
        <a class="navbar-brand col-lg-3 me-0" href="#">Centered nav</a>
        <ul class="navbar-nav col-lg-6 justify-content-lg-center">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" aria-disabled="true">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
        <div class="d-lg-flex col-lg-3 justify-content-lg-end">
          <button class="btn btn-primary">Button</button>
        </div>
      </div>
    </div>
  </nav>
    <%= render 'layouts/messages' %>
    <%= yield %>
  <!-- Include Bootstrap JavaScript via CDN -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>


  </body>
</html>

app/views/pages/home.html.erb
<h1>Home Page</h1>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <h2>The following errors prevent the user from being saved:</h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @user, data: { turbo: false }, local: true) do |f| %>
  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.submit(@user.new_record? ? "Sign up" : "Update account") %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Bloggers</h1>
<%= will_paginate @users %>
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Author</th>
    <th colspan="3">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>

    <tr>

      <td><%= link_to user.username, user  %></td>
      <td><%= link_to gravatar_for(user, size: 150), user %></td>
      <td><%= pluralize(user.articles.count, "article") %></td>
      <td><%= link_to "View Profile", user  %></td>
      <% if logged_in? %>
        <% if user == current_user %>
        <td><%= link_to "Edit Profile", edit_user_path(user)  %></td>
        <% end %>
        <% if current_user.admin? %>
        <td><%= link_to "Delete User", user_path(user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
        <% end %>
      <% end %>
      <td>Joined <%= time_ago_in_words(user.created_at) %> ago</td>
    </tr>
  <% end %>

  </tbody>
</table>
<%= will_paginate @users %>

app/views/users/new.html.erb
<h1>Signup for Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s profile</h1>

<%= gravatar_for @user %>

<% if logged_in? && @user == current_user %>
<%= link_to "Edit your profile", edit_user_path(@user) %>
<% end %>

<h3>Articles</h3>
<%= will_paginate @articles %>
<%= render '/articles/article' %>
<%= will_paginate @articles %>